name: Node CI (PR)
on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "tsconfig.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/**"

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

jobs:
  lint:
    name: Check linting issues
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build --noEmit
